mysite/blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

# config/urls.py 파일에 모든 요청을 받아서 분배
# config/urls.py 파일에서 guestbook/urls.py를 찾을 수 있게
# config/urls.py    blog/~~~
app_name = "blog"       # 반드시 필요함.
urlpatterns = [
    path("", views.index),     
    path("list2", views.getList2, name="blog_list2"),       # json 형태로 출력
    path("list", views.getList, name="blog_list"),          # html
    path("view/<id>", views.view, name="blog_view"),        # html에서 url 'blog:blog_view'
    path("write", views.write, name="blog_write"),        # html페이지로 이동
    path("save", views.save, name="blog_save"),          # 데이터를 받아서 디비에 저장
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include

# from pybo import views
# from blog import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("pybo/", include('pybo.urls')),
    path("blog/", include("blog.urls")),
    path("score/", include("score.urls")),
    path("guestbook/", include("guestbook.urls")),
    #path("blog/", views.index),     # url이 blog/인 경우 views.py 파일의 index함수 호출
    # path 함수가 url http://127.0.0.1:8000/blog
    # 를 blog/views.py파일의 index 함수를 연동
]

mysite/pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meat tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
    <!-- 네비게이션 바 -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- BootStrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script> 
</body>
</html>

mysite/templates/navbar.html
<!-- 네비게이션 바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="#">로그인</a>
                </li>
            </ul>
        </div>
    </div>
</nav>